language: cpp
script: echo "Deployed the output to https://transfer.sh/y4oYk/Mudlet-3.16.1-testing-PR2218-397d8a7.dmg"
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env:
    - Q_OR_C_MAKE=qmake

  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env:
    - Q_OR_C_MAKE=cmake

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=qmake
      QT_VERSION=510

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=cmake
      QT_VERSION=510

  - os: linux
    compiler: clang
    env:
    - Q_OR_C_MAKE=qmake
      QT_VERSION=510

  - os: linux
    compiler: clang
    env:
    - Q_OR_C_MAKE=cmake
      QT_VERSION=510

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=cmake
    - QT_VERSION=57 # actually Qt 5.7, used to check minimum supported Qt works
