language: cpp
script: exit 0
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env:
    - Q_OR_C_MAKE=qmake

  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env:
    - Q_OR_C_MAKE=cmake

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=qmake
      QT_VERSION=510

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=cmake
      QT_VERSION=510

  - os: linux
    compiler: clang
    env:
    - Q_OR_C_MAKE=qmake
      QT_VERSION=510

  - os: linux
    compiler: clang
    env:
    - Q_OR_C_MAKE=cmake
      QT_VERSION=510

  - os: linux
    compiler: gcc
    env:
    - Q_OR_C_MAKE=cmake
    - QT_VERSION=57 # actually Qt 5.7, used to check minimum supported Qt works
